---
- name: Provision AWS Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/default-vars.yml
    - ./credentials/tower_creds.yml
    - ./credentials/aws_resources.yml

  tasks:

    - name: Provision Instances on GCP
      block:

        - name: Provision Instances on GCP
          ansible.builtin.include_role:
            name: gcp-deploy
            tasks_from: provision-instances

      when: cloud_provider == "gcp"

    - name: Provision Instances on AWS
      block:

        - name: Provision Instances on AWS
          ansible.builtin.include_role:
            name: aws-deploy
            tasks_from: provision-instances

      when: cloud_provider == "aws"
