---
- block:
  - name: Wait for instances to be reachable
    ansible.builtin.wait_for_connection:
      sleep: 5
      timeout: 1000

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    become: yes
    when: tags.cloud_provider == "aws"
    
  - name: Install epel-release package
    ansible.builtin.dnf:
      name: epel-release
      state: present
    become: yes
    when: tags.cloud_provider == "aws"

  - name: Enable EPEL repository explicitly (if required)
    ansible.builtin.shell: dnf config-manager --set-enabled epel
    register: epel_enabled
    changed_when: "'enabled: True' in epel_enabled.stdout"
    become: yes
    when: tags.cloud_provider == "aws"

  - name: Verify EPEL repository is enabled
    ansible.builtin.shell: dnf repolist enabled | grep -i epel
    register: epel_check
    failed_when: epel_check.rc != 0
    become: yes
    when: tags.cloud_provider == "aws"


  - name: Ensure Python and pip are installed
    ansible.builtin.dnf:
      name: 
        - python3
        - python3-pip
      state: present
    become: yes
    when: tags.cloud_provider == "aws"

  - name: Install ansible-core via pip
    ansible.builtin.pip:
      name: ansible-core
      state: present
    become: yes
    when: tags.cloud_provider == "aws"
